language: node_js

node_js:
  - "stable"
  - "8"
  - "6"

cache:
  yarn: true
  directories:
    - "node_modules"

install:
  - yarn
  - npm run bootstrap
  - yarn global add codecov

script:
  - npm run lint
  - npm run typecheck
  - npm run testonly -- --coverage && codecov

notifications:
  email:
    on_success: never
