matrix:
  include:
    - language: node_js
      node_js:
        - "stable"
        - "8"
        - "6"
      cache:
        yarn: true
        directories:
          - "node_modules"
      install:
        - yarn
        - npm run bootstrap
        - yarn global add codecov

      script:
        - npm run lint
        - npm run typecheck
        - npm run testonly -- --coverage && codecov

    - language: ruby
      install: gem install awesome_bot
      script:
        - awesome_bot *.md --allow-dupe --white-list hooks.slack.com/services,example.com
        - for d in ./packages/*/ ; do (cd "$d" && echo "\ncd ${d}\n" && awesome_bot *.md --allow-dupe --white-list example.com,mycallback.com,petershats,jaspersmarket,airline.com,ngrok.io,hooks.slack.com/services,images.com,html-test,url.by,my.site.com); done

notifications:
  email:
    on_success: never
