environment:
  matrix:
    - nodejs_version: "10"

install:
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
# https://www.appveyor.com/updates/2017/10/22/
# already yarn v1.2.1
# - choco install yarn
  - yarn --version
  - yarn
  - npm run bootstrap

cache:
  - node_modules
  - "%LOCALAPPDATA%\\Yarn"

test_script:
  - npm run lint -- --color
  - npm run compile
  - npm run testonly -- --coverage --colors

# Don't actually build.
build: off
